name             'bcm-kafka'
maintainer       'Josh West'
maintainer_email 'josh_west@bose.com'
license          'All rights reserved'
description      'Installs/Configures bcm-kafka'
long_description 'Installs/Configures bcm-kafka'
version          '1.0.3'
depends          'java'
