name             'bcm-feeds'
maintainer       'Josh West'
maintainer_email 'josh_west@bose.com'
license          'All rights reserved'
description      'Installs/Configures bcm-feeds'
long_description 'Installs/Configures bcm-feeds'
version          '1.0.1'
depends          'python'
