name             'bcm-accounts'
maintainer       'Josh West'
maintainer_email 'josh_west@bose.com'
license          'All rights reserved'
description      'Installs/Configures bcm-accounts'
long_description 'Installs/Configures bcm-accounts'
version          '1.0.1'
depends          'users'
depends          'sudo'
