name             'bcm-base'
maintainer       'Josh West'
maintainer_email 'josh_west@bose.com'
license          'All rights reserved'
description      'Installs/Configures bcm-base'
long_description 'Installs/Configures bcm-base'
version          '1.0.10'
depends          'python'
